#!/bin/sh
# Permission to use, copy, modify, and/or distribute this software is granted.
# THIS SOFTWARE IS PROVIDED "AS IS", WITHOUT ANY WARRANTY, EXPRESS OR IMPLIED.

usage() {
	printf 'Usage: urn PATH [age options...]
If PATH is a directory, makes an encrypted archive of it.
If PATH is a file, decrypts & extracts directory from it.\n'
	return 0
}

make_tar() {
	if command -v pax >/dev/null 2>&1; then
		pax -x ustar -w "./$1"
	else
		tar c "./$1"
	fi
}

extract_tar() {
	if command -v pax >/dev/null 2>&1; then
		pax -r
	else
		tar x
	fi
}

urn() {
	path=$(realpath -- "$1") || return 1
	shift

	if [ -d "$path" ]; then
		cd "$(dirname "$path")" || return 1
		name=$(basename "$path")
		make_tar "$name" | age --encrypt "$@" -o "$OLDPWD/$name.tar.age"
	elif [ -f "$path" ]; then
		age --decrypt "$@" "$path" | extract_tar
	else
		printf 'urn: %s\n' "$path: No such file or directory"
		return 1
	fi
}

if [ "$1" ]; then urn "$@"; else usage; fi
